---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
# image will be published to ghcr.io/<user>/<name>
name: blue-desktop
# description will be included in the image's metadata
description: gmacdougall's wayblue based desktop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://mise.jdx.dev/rpm/mise.repo
    install:
      # Requirements for ruby-build
      - autoconf
      - gcc
      - rust
      - patch
      - make
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
      # General development
      - fd-find
      - fish
      - fzf
      - git-delta
      - mise
      - neovim
      - tmux
      # System stuff
      - fastfetch
      # Media
      - vlc
      # - micro
      # - starship
    remove: []
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: fonts
    fonts:
      nerd-fonts:
        - IBMPlexMono
        - Monaspace

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - com.valvesoftware.Steam
      - scope: user # Also add Flathub user repo, but no user packages 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
